name: ci-sonarcloud
on: 
  pull_request:
    branches:
      - develop
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test